# Generated by Django 3.2.25 on 2025-05-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bill_purchase_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='retail_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('superadmin', '超级管理员'), ('admin', '普通管理员'), ('customer', '普通用户')], default='customer', max_length=20),
        ),
    ]
