# Generated by Django 3.2.25 on 2025-05-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20250505_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_price',
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_stocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('pending', '待付款'), ('paid', '已付款'), ('returned', '已退货')], default='pending', max_length=20),
        ),
    ]
